[general]
enabled = true

[general.server-setting]
port = 50005
secret = "default" # todo: これを初回起動時に自動で設定してくれると良いな

[discord.general]
default-channel-id = "1362971564836130838"

[gateway]
[gateway.plugin-enabled]
[gateway.plugin-enabled.discord-notify]
enabled = true
channel-id = ""

[gateway.plugin-disabled]
[gateway.plugin-disabled.discord-notify]
enabled = true
channel-id = ""

[gateway.timeout]
check-interval = 1 # seconds, required server restart if changed.
timeout = 30 # seconds
enabled-logging = true

[gateway.timeout.discord-notify]
enabled = true
channel-id = ""
message-interval = 30 # seconds
max-message-loop = 5
notify-stop-button-pushable-user-ids = ["776726560929480707"]

[gateway.resumed]
[gateway.resumed.discord-notify]
enabled = true
channel-id = ""
