[general]

[discord.general]
default-channel-id = "1362971564836130838"

[discord.bot-token]
type = "system-environ" # "system-environ" or "raw-string"
value = "DiscordSRVBotToken"

[discord.webhook-url]
type = "raw-string"
value = "https://discord.com/api/webhooks/1364032685311393822/9aq4-tTr2L6VAiCynGPLCuqG05hmhVJc3fORzY8X8usVZ1WnzZeSm0R40fvplbSSdogX"

[message-share]
[message-share.in-servers]
[message-share.in-servers.player-chat]
enabled = true

[message-share.to-discord.player-chat]
enabled = true
channel-id = ""

[message-share.to-discord.player-chat.webhook]
enabled = true

[message-share.to-discord.join-leaves]
[message-share.to-discord.join-leaves.join]
enabled = true
channel-id = ""

[message-share.to-discord.join-leaves.leave]
enabled = true
channel-id = ""

[message-share.to-discord.boot-notify]
[message-share.to-discord.boot-notify.on-initialize]
enabled = true
channel-id = ""

[message-share.to-discord.boot-notify.on-shutdown]
enabled = true
channel-id = ""

[message-share]
[message-share.from-discord]
enabled = true # TODO: マイクラ側に比べてdiscordからの共有これしかないの？なんか機能増やせるでしょ
channel-id = ""
included-channel-ids = []
