[general]
plugin-message-prefix = "<green>[MetsChat]</green> "

[minecraft]
cross-server-message-format = "<hover:show_text:'from {senderServer}'>\\<<yellow>*</yellow>{senderName}></hover> {message}"
# placeholders: senderServer, senderName, message

[discord]
[discord.bot-token]
type = "system-environ" # "system-environ" or "raw-string"
value = "DiscordSRVBotToken"

[discord.channel-ids]
central-chat = "1362971564836130838"
boot-message = "1362971564836130838"

[discord.message-share.to-minecraft]
enabled = true
format = "[<click:open_url:'{discordMessageUrl}'><hover:show_text:'Discordで開く'><blue>Discord</blue></hover></click> | <hover:show_text:'{allRoleNames}'><color:#{roleColorHex}>{authorName}</color></hover>] {message}"
# placeholders: authorName, message, roleColorHex, allRoleNames, discordMessageUrl,
parse-markdown = true
