[general]
plugin-message-prefix = "<green>[MetsChat]</green> "

[minecraft]
[minecraft.cross-server-message-share]
enabled = true
format = "<hover:show_text:'from {senderServer}'>\\<<yellow>*</yellow>{senderName}></hover> {message}"
# placeholders: senderServer, senderName, message

[discord]
[discord.bot-token]
type = "system-environ" # "system-environ" or "raw-string"
value = "DiscordSRVBotToken"

[discord.channel-ids]
central-chat = "1362971564836130838"
boot-message = "1362971564836130838"

[discord.message-share.to-minecraft]
enabled = true
format = "[<click:open_url:'{discordMessageUrl}'><hover:show_text:'Discordで開く'><blue>Discord</blue></hover></click> | <hover:show_text:'{allRoleNames}'><color:#{roleColorHex}>{authorName}</color></hover>] {message}"
# placeholders: authorName, message, roleColorHex, allRoleNames, discordMessageUrl,
parse-markdown = true

[discord.message-share.to-discord]
enabled = true
[discord.message-share.webhook]
enabled = true
webhook-url = "https://discord.com/api/webhooks/1364032685311393822/9aq4-tTr2L6VAiCynGPLCuqG05hmhVJc3fORzY8X8usVZ1WnzZeSm0R40fvplbSSdogX"
author-icon-url = "https://mc-heads.net/combo/{uuid}"
# placeholders: mcid, uuid, uuidNoDashes, textureId
[discord.message-share.to-discord.formats]
sender = "{senderName}" # disable if `use-webhook` is false
message = "{message}"
# placeholders; senderName, message, serverName,