[general]
[general.backend-support]
enabled = true
[general.backend-support.server]
port = 50005
secret = "default" # todo: これを初回起動時に自動で設定してくれると良いな

[discord.general]
default-channel-id = "1362971564836130838"

[discord.bot-token]
type = "system-environ" # "system-environ" or "raw-string"
value = "DiscordSRVBotToken"

[discord.webhook-url]
type = "system-environ"
value = "MetsChatWebhookUrl"

[message-share]
[message-share.in-servers]
[message-share.in-servers.player-chat]
enabled = true

[message-share.in-servers.connection]
[message-share.in-servers.connection.server-change]
enabled = true

[message-share.to-discord.player-chat]
enabled = true
channel-id = ""

[message-share.to-discord.player-chat.webhook]
enabled = true

[message-share.to-discord.connection]
[message-share.to-discord.connection.join]
enabled = true
channel-id = ""

[message-share.to-discord.connection.leave]
enabled = true
channel-id = ""

[message-share.to-discord.connection.server-change]
enabled = true
channel-id = ""

[message-share.to-discord.boot-notify]
[message-share.to-discord.boot-notify.on-initialize]
enabled = true
channel-id = ""

[message-share.to-discord.boot-notify.on-shutdown]
enabled = true
channel-id = ""

[message-share.from-discord]
enabled = true # TODO: マイクラ側に比べてdiscordからの共有これしかないの？なんか機能増やせるでしょ
channel-id = ""
included-channel-ids = []
