[general]
plugin-message-prefix = "<green>[MetsChat]</green> "

[discord.general]
default-player-icon-url = "https://mc-heads.net/combo/{uuid}"
# placeholders: mcid, uuid, uuidNoDashes, textureId

[message-share]
[message-share.in-servers]
[message-share.in-servers.player-chat]
format = "<hover:show_text:'from {senderServer}'>\\<<yellow>*</yellow>{senderName}></hover> {message}"
# placeholders: senderServer, senderName, message

[message-share.in-servers.connection]
[message-share.in-servers.connection.server-change]
format = "<click:run_command:/server {nextServer}><aqua>{playerName}が{previousServer}から{nextServer}へ移動しました</aqua></click>"
# placeholders: playerName, previousServer, nextServer

[message-share.to-discord.player-chat]
content = "{message}"
# placeholders: senderName, message, serverName
[message-share.to-discord.player-chat.webhook]
author-icon-url = ""
# placeholders: mcid, uuid, uuidNoDashes, textureId
username = "{serverName} / {senderName}"
# placeholders: senderName, message, serverName

[message-share.to-discord.connection]
[message-share.to-discord.connection.join]
author-icon-url = ""
author-name = "{playerName} が {serverName} に参加しました"
desc = ""
# placeholders: playerName, serverName, playersCount, maxPlayers
color = "#66ff66"

[message-share.to-discord.connection.leave]
author-icon-url = ""
author-name = "{playerName} がサーバーから退出しました"
desc = ""
# placeholders: playerName, playersCount, maxPlayers
color = "#ff6666"

[message-share.to-discord.connection.server-change]
author-icon-url = ""
author-name = "{playerName} が {previousServer} から {nextServer} へ移動しました"
desc = ""
# placeholders: playerName, previousServer, nextServer
color = "#6666ff"

[message-share.to-discord.boot-notify]
[message-share.to-discord.boot-notify.on-initialize]
title = 'プロキシが起動しました'
desc = "Proxy: {proxyVersion}\nRAM: {usedRamMB}/{maxRamMB}MB\nDiscord Latency: {discordLatency}ms"
content = ""
# placeholders: proxyVersion, maxRamMB, usedRamMB, discordLatency
color = "#00ff00"

[message-share.to-discord.boot-notify.on-shutdown]
title = 'プロキシが停止しました'
desc = '異常終了と思われる場合、管理者に連絡してください'
content = "<@776726560929480707>" # mention of crab55e
color = "#ff0000"

[message-share.from-discord]
format = "[<click:open_url:'{discordMessageUrl}'><hover:show_text:'Discordで開く'><blue>Discord</blue></hover></click> | <hover:show_text:'{allRoleNames}'><color:#{roleColorHex}>{authorName}</color></hover>] {message}"
# placeholders: authorName, message, roleColorHex, allRoleNames, discordMessageUrl
parse-markdown = true
all-role-names-separator = ", "

[command]
[command.base]
format = "Running {pluginVersion}"
# placeholders: pluginVersion

[command.reload]
format = "Reloaded configurations"
# placeholdders: configFileNames

[command.jda]
format = """
MetsChat / JDA
Status: {discordClientStatus},
Latency: {discordLatency}ms"""
# placeholders: discordClientStatus, discordLatency

[command.jda.reconnect]
format = "Unavailable feature." # 実装したかったが無理そう。未来の自分に任せるよ