[general]
plugin-message-prefix = "<green>[MetsChat]</green> "

[discord.general]
default-player-icon-url = "https://mc-heads.net/combo/{uuid}"
# placeholders: mcid, uuid, uuidNoDashes, textureId

[discord.commands]
command-disabled-message = "このコマンドは無効化されています"

[discord.commands.playerlist]
format = "**{currentPlayers}/20** ```{playerNames}```"
# placeholders: currentPlayers, playerNames
player-name-separator = ", "
no-players = "現在サーバー内にプレイヤーはいません"

[message-share]
[message-share.in-servers]
[message-share.in-servers.player-chat]
format = "<hover:show_text:'from {senderServer}'>\\<<yellow>*</yellow>{senderName}></hover> {message}"
# placeholders: senderServer, senderName, message

[message-share.in-servers.connection]
[message-share.in-servers.connection.server-change]
format = '<click:run_command:/server {nextServer}><hover:show_text:"クリックでついていく"><aqua>{playerName}が{previousServer}から{nextServer}へ移動しました</aqua></hover></click>'
# placeholders: playerName, previousServer, nextServer

[message-share.to-discord.player-chat]
content = "{message}"
# placeholders: senderName, message, serverName
[message-share.to-discord.player-chat.webhook]
author-icon-url = ""
# placeholders: mcid, uuid, uuidNoDashes, textureId
username = "{serverName} / {senderName}"
# placeholders: senderName, message, serverName

[message-share.to-discord.connection]
[message-share.to-discord.connection.join]
author-icon-url = ""
author-name = "{playerName} が {serverName} に参加しました"
desc = ""
# placeholders: playerName, serverName, playersCount, maxPlayers
color = "#66ff66"

[message-share.to-discord.connection.leave]
author-icon-url = ""
author-name = "{playerName} がサーバーから退出しました"
desc = ""
# placeholders: playerName, playersCount, maxPlayers
color = "#ff6666"

[message-share.to-discord.connection.server-change]
author-icon-url = ""
author-name = "{playerName} が {previousServer} から {nextServer} へ移動しました"
desc = ""
# placeholders: playerName, previousServer, nextServer
color = "#6666ff"

[message-share.to-discord.boot-notify]
[message-share.to-discord.boot-notify.on-initialize]
title = 'プロキシが起動しました'
desc = "**Proxy**: {proxyVersion}\n**RAM**: {usedRamMB}/{maxRamMB}MB\n**Discord Latency**: {discordLatency}ms"
content = ""
# placeholders: proxyVersion, maxRamMB, usedRamMB, discordLatency
color = "#00ff00"

[message-share.to-discord.boot-notify.on-shutdown]
title = 'プロキシが停止しました'
desc = '異常終了と思われる場合、管理者に連絡してください'
content = "<@776726560929480707>" # mention of crab55e
color = "#ff0000"

[message-share.from-discord]
format = "[<click:open_url:'{discordMessageUrl}'><hover:show_text:'Discordで開く'><blue>Discord</blue></hover></click> | <hover:show_text:'{allRoleNames}'><color:#{roleColorHex}>{authorName}</color></hover>] {message}"
# placeholders: authorName, message, roleColorHex, allRoleNames, discordMessageUrl
parse-markdown = true
all-role-names-separator = ", "

[backend-support]
[backend-support.plugin-enabled]
[backend-support.plugin-enabled.discord-notify]
title = "バックエンドサーバー {backendServer} が接続されました"
desc = ""
content = ""
# placeholders: backendServer
color = "#00ff00"

[backend-support.plugin-disabled]
[backend-support.plugin-disabled.discord-notify]
title = "バックエンドサーバー {backendServer} が切断されました"
desc = ""
content = ""
# placeholders: backendServer
color = "#ff0000"

[backend-support.timeout]
[backend-support.timeout.discord-notify]
title = "バックエンドサーバー {backendServer} のタイムアウトを検知しました"
desc = "最後の応答: <t:{lastHeartbeatUnix}:R> / `{backendServer}`\nバックエンドサーバーが正常に終了している場合アラートを停止してください"
content = "<@776726560929480707>"
# placeholders: backendServer, lastHeartbeatUnix
color = "#ff0000"
stop-button-label = "アラートを停止"
notify-stopped-message = "アラートを停止しました"
notify-already-stopped-message = "アラートは既に停止しています"
stop-button-permission-denied = "アラート停止ボタンを押す権限がありません。"

[backend-support.resumed]
[backend-support.resumed.discord-notify]
title = "バックエンドサーバー {backendServer} のタイムアウトからの復旧を検知しました"
desc = "最後のタイムアウト: <t:{lastTimeoutUnix}:T>"
content = "<@776726560929480707>"
# placeholders: backendServer, lastTimeoutUnix
color = "#ff0000"

[backend-support.player-events]
[backend-support.player-events.on-death]
[backend-support.player-events.on-death.in-servers]
format = "<hover:show_text:'from {eventServer}'><yellow>*</yellow>{message}</hover>"
# placeholders: eventServer, message
[backend-support.player-events.on-death.discord]
author-icon-url = ""
# placeholders: mcid, uuid, uuidNoDashes
author-name = "{eventServer} / {message}"
# placeholders: eventServer, message
color = "#4c4c54"

[backend-support.player-events.on-advancement-done]
[backend-support.player-events.on-advancement-done.in-servers]
format = "<hover:show_text:'from {eventServer}'><yellow>*</yellow>{message}</hover>"
# placeholders: eventServer, message
[backend-support.player-events.on-advancement-done.discord]
author-icon-url = ""
# placeholders: mcid, uuid, uuidNoDashes
author-name = "{eventServer} / {message}"
# placeholders: eventServer, message
color = "#4c4c54"

[command]
[command.base]
format = "{pluginVersion} を実行中"
# placeholders: pluginVersion

[command.reload]
format = "設定を再読み込みしました"
# placeholdders: configFileNames

[command.jda]
format = """
MetsChat / JDA
ステータス: {discordClientStatus},
Ping: {discordLatency}ms"""
# placeholders: discordClientStatus, discordLatency

[command.jda.reconnect]
format = "未実装の機能" # 実装したかったが無理そう。未来の自分に任せるよ

[command.jda.cancel-requests]
success = "{cancelledRequestCount}件のリクエストをキューから削除しました"
# placeholders: cancelledRequestCount
failed = "<red>JDAにアクセスできませんでした。</red>"
